#!/bin/bash

set -e -x

env

BUILD_DATE=`date -u +%Y-%m-%dT%H:%M:%SZ`

[ -z "$DOCKERFILE_PATH" ]   && DOCKERFILE_PATH="Dockerfile"

[ -z "$VCS_REF" ]           && VCS_REF="$SOURCE_COMMIT"
[ -z "$VCS_REF" ]           && VCS_REF=`git rev-parse --short HEAD`

[ -z "$VCS_URL" ]           && VCS_URL=`git config --get remote.origin.url`
[ -z "$VCS_TAG" ]           && VCS_TAG=`git --no-pager tag --points-at "$VCS_REF" | head -n 1`

[ -z "$VCS_BRANCH" ]        && VCS_BRANCH="$SOURCE_BRANCH"
[ -z "$VCS_BRANCH" ]        && VCS_BRANCH=`git rev-parse --abbrev-ref HEAD`


[ -z "$BUILD_VERSION" ]     && BUILD_VERSION="$DOCKER_TAG"
[ -z "$BUILD_VERSION" ]     && BUILD_VERSION="${VCS_TAG}"
[ -z "$BUILD_VERSION" ]     && BUILD_VERSION="${VCS_BRANCH}-${VCS_REF}"

[ -z "$DOCKER_REPO" ]       && DOCKER_REPO="magesuite/bundle-theme-js"
[ -z "$DOCKER_TAG" ]        && DOCKER_TAG="${BUILD_VERSION}"
[ -z "$IMAGE_NAME" ]        && IMAGE_NAME="${DOCKER_REPO}:${DOCKER_TAG}"

docker build \
    --file "$DOCKERFILE_PATH" \
	--label org.label-schema.version=$BUILD_VERSION \
    --label org.label-schema.build-date=$BUILD_DATE \
    --label org.label-schema.vcs-url=$VCS_URL \
    --label org.label-schema.vcs-ref=$VCS_REF \
	--tag $IMAGE_NAME .
